Add back previous run and profile updates
demml/scouter-server pull request #19
Opened 2024-09-05 20:47 UTC by thorrester

## Pull Request

### Short Summary
-Adds back `previous_run` from the `drift_profile` table and use it in the limit timestamp clause.

2024-09-05 20:52 UTC, thorrester commented on src/alerts/drift.rs
> +            &nd_feature_arr.t().view(), // need to transpose because calculation is done at the row level across each feature
This is to ensure feature len matches what is expected since we loop over each row and then loop over each feature in a row

2024-09-05 20:53 UTC, thorrester commented on src/alerts/drift.rs
> +        let mut transaction: sqlx::Transaction<Postgres> = self.db_client.pool.begin().await?;
removed the loop here since it's already running in a loop

2024-09-05 20:54 UTC, thorrester commented on src/api/handler.rs
> +pub async fn update_drift_profile_status(
new logic for updating a profiles status. Once it's activated to `true`, the background tasks should pick it up

2024-09-05 20:54 UTC, thorrester commented on src/main.rs
> +const NUM_WORKERS: usize = 3;
I think we can make these in env vars later on

2024-09-05 20:54 UTC, thorrester commented on src/main.rs
> +    for i in 0..NUM_DISPATCHERS {
changed to a loop to create n background scheduler tasks

2024-09-05 20:55 UTC, thorrester commented on src/sql/postgres.rs
> +            active: false,
user must opt-in to monitoring or else anytime someone create a drift profile, the monitoring job will pick it up

2024-09-05 20:56 UTC, thorrester commented on tests/drift_integration.rs
> +#[tokio::test]
test to use new populate script

2024-09-05 21:24 UTC, russellkemmit commented on src/main.rs
> +    for i in 0..NUM_DISPATCHERS {
Need this loop to ensure we process all active profiles

2024-09-05 21:44 UTC, russellkemmit requested changes

2024-09-05 21:44 UTC, russellkemmit commented on src/main.rs
> +    for i in 0..NUM_DISPATCHERS {
Hell Yes!!!

2024-09-05 21:44 UTC, russellkemmit commented on src/alerts/drift.rs
> +        let mut transaction: sqlx::Transaction<Postgres> = self.db_client.pool.begin().await?;
This loop is needed to ensure all profiles are processed.

2024-09-05 21:45 UTC, russellkemmit commented on tests/drift_integration.rs
> +#[tokio::test]
Let's GO!!

2024-09-06 02:20 UTC, thorrester commented
Added loop back + made some additional changes
- Better naming for functions
- Additional error handling if drift array is empty
- Added sleep for when there's nothing left to process in order to add a little bit of a delay
- Changed the naming in the makefile

2024-09-06 19:18 UTC, merged